language: r

install:
 - R -e "0" --args --bootstrap-packrat

cache: 
  packages: yes
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
  - $TRAVIS_BUILD_DIR/packrat/


before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script: 
  - ./_build.sh
  - ./_deploy.sh
