language: r
sudo: false
cache: 
  packages: yes
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files

before_script:
  - chmod +x bookdown_files/_build.sh
  - chmod +x bookdown_files/_deploy.sh

script:
  - ./bookdown_files/_build.sh
  - ./bookdown_files/_deploy.sh
